spring:
  datasource:
    url: jdbc:mysql://43.138.64.174:3306/opt_helper
    username: DB_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /

mybatis:
  mapper-locations:
    classpath:/mapper/*.xml