spring:
  datasource:
    url: jdbc:mysql://43.138.64.174:3306/opt_helper
    username: DB_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

server:
  port: 8081
  servlet:
    context-path: /

mybatis:
  mapper-locations:
    classpath:/mapper/*.xml